# Flask App Configuration
flask:
  # Basic settings
  replicas: 5
  # Image settings
  image:
    repository: sreevasmk1993/employees-data-app
    tag: b96caa379707e024c9b9d80ee3391b3678b004f2
  # Port
  containerPort: 3000
  # Health check paths
  probes:
    liveness:
      path: /status # Health check endpoint
    readiness:
      path: /status # Same endpoint
  # Resource limits
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  # Autoscaling
  autoscaling:
    minReplicas: 5
    maxReplicas: 8
    cpuTarget: 50
    memoryTarget: 70
secrets:
  serviceAccountName: default
# Argocd
argocd:
  enabled: false # Set to false if not using ArgoCD
monitoring:
  enabled: true
  namespace: monitoring
